export const DATA_LOAD= "DATA_LOAD";
export const ITEM_HEADER_COLLAPSE= "ITEM_HEADER_COLLAPSE";
export const PROMO_HEADER_COLLAPSE= "PROMO_HEADER_COLLAPSE";
export const PROMO_CODE_APPLIED= "PROMO_CODE_APPLIED";